title: Atelier Abbey
author: Atelier Abbey
email: info@atelierabbey.org
description: > # this means to ignore newlines until "baseurl:"
  Atelier Abbey seeks to bring art education and resources to all.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

theme: minima
